spring:
  application:
    name: portfolio-dashboard
  datasource:
    url: jdbc:h2:mem:ptfdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
