spring:
  application:
    name: portfolio-dashboard

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

portfolio:
  input: ${PORTFOLIO_FILE:classpath:sample-input.csv}
